export interface Language {
  code: string;
  name: string;
  nativeName: string;
  region: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'International' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'North India' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra Pradesh' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'North India' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر', region: 'Kashmir' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', region: 'Sindh' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', region: 'Sikkim' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', region: 'Classical' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी', region: 'Goa' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্', region: 'Manipur' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी', region: 'Jammu' },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ', region: 'Jharkhand' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली', region: 'Bihar' },
  { code: 'bh', name: 'Bhojpuri', nativeName: 'भोजपुरी', region: 'Bihar' },
];

// Translation dictionary for common UI strings
export const translations: Record<string, Record<string, string>> = {
  en: {
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    customers: 'Customers',
    conversations: 'Conversations',
    itineraries: 'Itineraries',
    newChat: 'New Chat',
    send: 'Send',
    typeMessage: 'Type your message...',
    logout: 'Logout',
    settings: 'Settings',
    budget: 'Budget',
    balanced: 'Balanced',
    comfort: 'Comfort',
    flights: 'Flights',
    hotels: 'Hotels',
    totalCost: 'Total Cost',
    duration: 'Duration',
    bookNow: 'Book Now',
    waitForBetterPrice: 'Wait for Better Price',
    priceRising: 'Price Rising',
    priceStable: 'Price Stable',
    priceDropping: 'Price Dropping',
    warning: 'Warning',
    risk: 'Risk',
    explanation: 'Why this option?',
    generateMessage: 'Generate Message',
    followUpReminder: 'Follow-up Reminder',
    bookingChecklist: 'Booking Checklist',
    selectLanguage: 'Select Your Preferred Language',
    continueToApp: 'Continue to App',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    enterOtp: 'Enter OTP',
    verifyOtp: 'Verify OTP',
    sendOtp: 'Send OTP',
    resendOtp: 'Resend OTP',
    cheapest: 'Cheapest',
    fastest: 'Fastest',
    mostComfortable: 'Most Comfortable',
    tradeoffControl: 'Preference Slider',
    addCustomer: 'Add Customer',
    customerName: 'Customer Name',
    customerEmail: 'Customer Email',
    customerPhone: 'Phone Number',
    preferences: 'Preferences',
    notes: 'Notes',
    save: 'Save',
    cancel: 'Cancel',
    noConversations: 'No conversations yet',
    startNewChat: 'Start a new chat to begin',
  },
  hi: {
    welcome: 'स्वागत है',
    dashboard: 'डैशबोर्ड',
    customers: 'ग्राहक',
    conversations: 'बातचीत',
    itineraries: 'यात्रा कार्यक्रम',
    newChat: 'नई चैट',
    send: 'भेजें',
    typeMessage: 'अपना संदेश लिखें...',
    logout: 'लॉग आउट',
    settings: 'सेटिंग्स',
    budget: 'बजट',
    balanced: 'संतुलित',
    comfort: 'आरामदायक',
    flights: 'उड़ानें',
    hotels: 'होटल',
    totalCost: 'कुल लागत',
    duration: 'अवधि',
    bookNow: 'अभी बुक करें',
    waitForBetterPrice: 'बेहतर कीमत का इंतजार करें',
    priceRising: 'कीमत बढ़ रही है',
    priceStable: 'कीमत स्थिर है',
    priceDropping: 'कीमत गिर रही है',
    warning: 'चेतावनी',
    risk: 'जोखिम',
    explanation: 'यह विकल्प क्यों?',
    generateMessage: 'संदेश बनाएं',
    followUpReminder: 'फॉलो-अप रिमाइंडर',
    bookingChecklist: 'बुकिंग चेकलिस्ट',
    selectLanguage: 'अपनी पसंदीदा भाषा चुनें',
    continueToApp: 'ऐप पर जारी रखें',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    email: 'ईमेल',
    enterOtp: 'OTP दर्ज करें',
    verifyOtp: 'OTP सत्यापित करें',
    sendOtp: 'OTP भेजें',
    resendOtp: 'OTP दोबारा भेजें',
    cheapest: 'सबसे सस्ता',
    fastest: 'सबसे तेज',
    mostComfortable: 'सबसे आरामदायक',
    tradeoffControl: 'प्राथमिकता स्लाइडर',
    addCustomer: 'ग्राहक जोड़ें',
    customerName: 'ग्राहक का नाम',
    customerEmail: 'ग्राहक का ईमेल',
    customerPhone: 'फ़ोन नंबर',
    preferences: 'प्राथमिकताएं',
    notes: 'नोट्स',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    noConversations: 'अभी तक कोई बातचीत नहीं',
    startNewChat: 'शुरू करने के लिए नई चैट शुरू करें',
  },
};

export const getTranslation = (lang: string, key: string): string => {
  return translations[lang]?.[key] || translations['en']?.[key] || key;
};